### ISSUE TITLE
Which is the Genes file

### ISSUE THREAD

**Issue by lpoorvin** [jtamames/SqueezeMdb#1]
In the docs under "Creating databases..." the description for the genes file is the *.mergedtable file.  There was no file matching that description generated when I ran SqueezeMeta.  Does the genes file have a different name or was there a problem when I ran SqueezeMeta and it wasn't generated?
Thanks!

**Comment by fpusan** [comment]
Hi! The right file would be the 12.*.orftable one. We changed the name and
forgot to update the documentation here.
