### ISSUE TITLE
Error in bin file?

### ISSUE THREAD

**Issue by lpoorvin** [jtamames/SqueezeMdb#2]
After uploading the files to create a project, I get an error:

`Error in bin file: Wrong header: Unknown sample name '3P' in column 11`

3P is the name of one of two samples listed in the samples file.  The contents of the samples file are:
```
3P	3Pfilt.fastq	pair1
4P	4Pfilt.fastq	pair1
```
The samples were unpaired Oxford Nanopore reads.  The SqueezeMeta run did not appear to have any issues.  Any ideas as to the problem?  Thanks!

**Comment by fpusan** [comment]
The samples file required for the DB does not have the same format as the one used in SqueezeMeta. I just realized that I did not include that in the documentation.

For the DB, you need a tab-separated file containing the sample names and any other metadata available. In the example attached, I include a mock metadata field called "test"

```
Sample           test
SRR1927149       1
SRR1929489       2
```

I will update the documentation.

**Comment by fpusan** [comment]
Also would you mind sending us the 21.*.stats file from your SqueezeMeta run? This file only contains basic assembly, mapping, annotation and binning statistics. We don't have that many tests using Oxford Nanopore data, and we'd like to take a look at how it went, if it's ok with you.

**Comment by lpoorvin** [comment]
I've emailed the stats file with some additional run info.  After creating a samples file based upon your suggestion, I get a new error when trying to create a project;

> Error in bin file: Wrong header: Missing column 'Chimerism'

**Comment by fpusan** [comment]
Hopefully fixed.
Get the latest commit from SqueezeMdb and reinstall.

Also get the latest commit (8380b3dc7ce43384d504c6472c4d81ece8e526ff) from SqueezeMeta, and re-run step 12:

`.../SqueezeMeta/scripts/12.mergeannot2.pl <YourProjectName>`

Let me know if this works for you.

**Comment by lpoorvin** [comment]
That worked perfectly, was able to get a project created.  Thanks!

**Comment by fpusan** [comment]
Thanks to you! Closing the issue
