### ISSUE TITLE
It showing blank screen after installtion.

### ISSUE THREAD

**Issue by vmevada102** [jtamames/SqueezeMdb#5]
As per the instructions here, i jave installed this properly. 

After successful installation, the http://  to transferred to https:// protocol and showing blank screen instead of Login screen

**Comment by fpusan** [comment]
Hi! Unfortunately we no longer maintain this, as the person  who coded it in the first place is no longer be available. We replaced all the querying functionality with the SQMtools R package, details can be found in the main SqueezeMeta repo
